### ISSUE TITLE
Mounting volumes does not work

### ISSUE THREAD

**Issue by Semetra22** [benjaminbear/docker-ddns-server#10]
Sorry for the question but I can't get the image to work. 
It seems that mounting the volumes does not work. 
Both with docker-compose and docker-run I get the error.

`ERROR: for ddns  Cannot start service ddns: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/docker/ddns/database" to rootfs at "/root/dyndns/database" caused: mount through procfd: open o_path procfd: open /var/lib/docker/overlay2/ef39d03481702de8c0a78268fdbc289a44817d9a0c1bb2ec4f50c381a3b382ee/merged/root/dyndns/database: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
`

OS: Alpine Linux 3.14.1
Docker version: 20.10.7

**Comment by benjaminbear** [comment]
Could you add the whole "docker run" command and a "ls -la" on the mounting point "/home/docker/ddns/database" for further investigations?

**Comment by Semetra22** [comment]
Sure, 
here´s my docker run command: 
`docker run -it -d \
    -p 8080:8080 \
    -p 5353:53 \
    -p 5353:53/udp \
    -v /home/docker/ddns/bind-data:/var/cache/bind \
    -v /home/docker/ddns/database:/root/dyndns/database \
    -e DDNS_ADMIN_LOGIN=admin:123455546. \
    -e DDNS_DOMAINS=dyndns.example.com \
    -e DDNS_PARENT_NS=ns.example.com \
    -e DDNS_DEFAULT_TTL=3600 \
    --name=dyndns \
    bbaerthlein/docker-ddns-server:latest`
     
    I have of course adjusted the Domain and Parent NS. The data here serve as an example
    Here´s my directory
    
docker01:/home/docker/ddns# ls -la
drwxr-xr-x    4   root     root          4096  .
drwxr-xr-x    10 root     root          4096  ..
drwxr-xr-x    2   root     root          4096  bind-data
drwxr-xr-x    2   root     root          4096  database

**Comment by LucaOverflow** [comment]
Same issue here. For me it looks like the path inside of the container doesnt exist.
![image](https://user-images.githubusercontent.com/44546543/129480936-c0a4d547-aa45-4dc0-8657-1e94f0fd584c.png)

There is a file called dyndns in the root directory but not a folder. However there is a database folder with a ddns.db file in it.. Could the database folder be the actual folder to bind to the volume?

I'm gonna try a litte bit around for myself and will post again if I find something useful.

**Comment by benjaminbear** [comment]
looks like the database is created at the wrong place, have to test this out. 
The mounting path ist wrong: you have to use "root/database" instead! 

I will fix it in the documentation
