### ISSUE TITLE
Logs should be listed descending

### ISSUE THREAD

**Issue by ebelmxi** [benjaminbear/docker-ddns-server#13]
In my opinion, the logs page currently has no advantage because only the first 30 logs are listed and I cannot see the last updates.
The best solution is probably paging, but I think it's an advantage if you can see the "last" 30 logs.

**Comment by benjaminbear** [comment]
This makes sense. Thank you for reporting!

**Comment by benjaminbear** [comment]
Its fixed with v1.1.0
