### ISSUE TITLE
provide multi-arch containers

### ISSUE THREAD

**Issue by maltegrosse** [benjaminbear/docker-ddns-server#15]
would be great to have multi arch containers (arm and arm64), its simple to setup with github actions for public repositories:

see https://github.com/maltegrosse/zero-ui-noauth/blob/main/.github/workflows/container.yml

**Comment by benjaminbear** [comment]
Thank you for the feedback. Wanted this to be done anyway, will apply it very soon!

**Comment by maltegrosse** [comment]
sounds great - let me know if some PRs welcome - just abit weird for for github actions :)
some off topic: does your ddns server allows wildcard subdomains? *.sub.ddns.main.tld ?

**Comment by maltegrosse** [comment]
see https://github.com/maltegrosse/docker-ddns-server/blob/master/.github/workflows/containers.yml
and PR #17

**Comment by benjaminbear** [comment]
done with your PR
