### ISSUE TITLE
Host Entry -> short Usernames not possible?

### ISSUE THREAD

**Issue by nibelungen** [benjaminbear/docker-ddns-server#18]
Hi and thanks for this handy tool,

as i had a ddns service before i have some clients rolled out and want to
add them to the new service - the usernames and passwords were really short and i dont want
to change them on the clients - is there a way to disable the check for these fields (username / password)??

Currently i get the following warning:

Error: Key: 'Host.UserName' Error:Field validation for 'UserName' failed on the 'min' tag

Thanks in advance.

**Comment by maltegrosse** [comment]
Hi,
it is related to the gorm model and the minimum characters (8), see
https://github.com/benjaminbear/docker-ddns-server/blob/56c46933a6666bf9c9dfb6b6b4db2e7252c8876b/dyndns/model/host.go#L17

**Comment by benjaminbear** [comment]
To be honest, we can reduce it to 3 characters.. :)
