### ISSUE TITLE
1 Character Host Names + More

### ISSUE THREAD

**Issue by X791105** [benjaminbear/docker-ddns-server#19]
Hi, I am trying to migrate from MintDNS on Windows Server 2012 to this awesome replacement, but I am running into a few issues:

1. When I try to create a hostname with just a single character (such as _a.example.com_, I get the following error:
	> Error: Key: 'Host.Hostname' Error:Field validation for 'Hostname' failed on the 'hostname' tag`

	Where can I edit and remove this restriction?

2. I was able to remove the 8-character minimum restrictions for usernames and passwords, but I was wondering, is it possible to not limit hostnames to unique usernames? I would like to be able to assign multiple hosts to the same user (that way current hosts assigned to the same user can continue to resolve without the login information needing to change.

3.  How can I make both hostnames and usernames case INsensitive on creation, edit and ddns updates? I would like that regardless of how they are inputted (on creation of hostname and edits) or received for DDNS Update, that they are always translated to lowercase and stored that way.

Any help would be appreciated. Thanks in advance.

**Comment by benjaminbear** [comment]
Hi!

For #1: Didn't test it, but I guess the "hostname" validator could be the reason: https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/model/host.go#L12 Simply try to remove it and see if its solving your problem.
 
#2: Unfortunately there is no "user management" right now. I would be a quite huge change on the code. What about setting the same user and password to the different host? Does that work? EDIT: you have to remove that "unique" here https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/model/host.go#L17

#3:  I agree with hostnames, but I'm not sure about usernames :/ Do you have a fork? I will try to help you on that.

**Comment by X791105** [comment]
> Hi!
>
Thank you very much for taking the time to respond, I really appreciate that.


 
> For #1: Didn't test it, but I guess the "hostname" validator could be the reason: https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/model/host.go#L12 Simply try to remove it and see if its solving your problem.
> 
Yes, that was the reason, removing it solved the problem.



> #2: Unfortunately there is no "user management" right now. I would be a quite huge change on the code. What about setting the same user and password to the different host? Does that work? EDIT: you have to remove that "unique" here https://github.com/benjaminbear/docker-ddns-server/blob/master/dyndns/model/host.go#L17
> 
That worked, although for existing database, I had to manually modify the _hosts_ table too.



> #3: I agree with hostnames, but I'm not sure about usernames :/ Do you have a fork? I will try to help you on that.
> 
My fork is at https://github.com/X791105/docker-ddns-server and yes, please do help me. Thanks.

**Comment by ivancarlosti** [comment]
I had same problem related to "Error:Field validation for 'Hostname'"
Commented line 12 of file host.go and ir worked fine.
Not clear to me if it is an issue related to local DNS resolver or becayse I am using an ususual domain (.gg)
