### ISSUE TITLE
Validation for domain should be "fqdn" instead of "hostname"

### ISSUE THREAD

**Issue by trading-peter** [benjaminbear/docker-ddns-server#35]
My ddns domain has a single letter component. Like this for example:
myhost.d.example.com

The ".d." fails the validation tag "hostname" of github.com/go-playground/validator.
Afaik there is no reason that the domain should be validated as a hostname. It should rather be the fqdn validator tag.

**Comment by benjaminbear** [comment]
Got changed :)
