### ISSUE TITLE
Add an option to prevent ipv6 updates

### ISSUE THREAD

**Issue by Gagi2k** [benjaminbear/docker-ddns-server#5]
I have some services running at home which don't work with ipv6 addresses (on the server side), but as my router is updating both addresses (and i cannot configure it there), the clients will always get the ipv6 address and fail to connect.

What i've noticed, is that when only the A entry of the DNS is set, the client resolves only the ipv4 address and the connection works fine. For those cases it would be great if there is a flag to prevent ipv6 entries of a certain host.

**Comment by benjaminbear** [comment]
I think blocking ipv6 won't be a feature in the future

**Comment by Gagi2k** [comment]
I agree, i digged deeper into the problem and realized, the whole DDNS system needs to be different to support ipv6 for the average home user.

I see the following problem. The router at home is updating the dyndns service with it's current IP. The ipv4 adresss will be the single public IP address for the whole network, everything else will be using NAT behind this public ipv4. You usually use some port forwarding to expose the services and everything is fine.

But with ipv6 the address which gets updated is not the single public address anymore, as it will get the ipv6 of the router and most routers don't do NAT for ipv6. In this case the ipv6 address is updated correctly, but it's not useful as the actual service is not running on your router.

Looking at some other ipv6 dyndns services, it seems they are doing it like this: A dydns entry is created which has the local ipv6 address of the device you want to expose. That alone won't work, but the entry will be using the prefix from the router ipv6 address and by that calculate the correct ipv6 address for the service you want to provide.

Let me know what you think.
